baseURL = "/"
languageCode = "en"
title = ""
# theme = "doks"  # Disabled: using Hugo Modules mounts instead
defaultContentLanguage = "en"
# Disable kinds: keep section enabled so /blog/ and posts are generated
disableKinds = ["home", "taxonomy", "term", "RSS"]

[params]
  # UI minimization
  search = false
  showEditPage = false
  showLastMod = false
  showSidebar = false
  showBreadcrumbs = false
  showNavbar = true
  showFooter = false
  # Theme toggle
  colorMode = "auto"
  showThemeToggle = true

[outputs]
  home = ["HTML"]

[permalinks]
  blog = "/blog/:slug/"
