baseURL = "/"
languageCode = "ru"
title = "Таро Расклад"
defaultContentLanguage = "en"
disableKinds = ["home", "taxonomy", "term", "section", "RSS"]

[params]
  search = false
  showEditPage = false
  showLastMod = false
  showSidebar = false
  showBreadcrumbs = false
  showNavbar = false
  showFooter = false
  colorMode = "auto"
  showThemeToggle = true

[outputs]
  home = ["HTML"]

[permalinks]
  blog = "/blog/:slug/"
