# Hugo
title = "Blog"
description = "Minimal blog"
images = ["cover.png"]

# show only blog in main sections
mainSections = ["blog"]

[social]
  twitter = ""

# Doks
[doks]
  colorMode = "auto"
  colorModeToggler = true

  # Navbar
  navbarSticky = true
  containerBreakpoint = "lg"
  navBarButton = false

  # Disable search and extras
  flexSearch = false
  showSearch = []
  indexSummary = false

  # Nav/UX cleanup
  sectionNav = []
  toTopButton = false
  breadcrumbTrail = false
  headlineHash = false
  scrollSpy = false
  headerBar = false
  backgroundDots = false

  # Homepage blocks off
  sectionFooter = false

  # Blog
  relatedPosts = false
  imageList = false
  imageSingle = true

  # Repo/UI
  editPage = false
  lastMod = false

# Render hooks
[render_hooks.image]
  errorLevel = 'ignore'
[render_hooks.link]
  errorLevel = 'ignore'
  highlightBroken = false

# Images
[thulite_images]
  [thulite_images.defaults]
    decoding = "async"
    fetchpriority = "auto"
    loading = "lazy"
    widths = [480, 768, 1025, 1440]
    sizes = "auto"
    process = ""
    lqip = "16x webp q20"

[inline_svg]
  iconSetDir = "tabler-icons"

[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "favicon.png"
    svgIcon = "favicon.svg"
    maskIcon = "mask-icon.svg"
    maskIconColor = "white"
  [seo.schemas]
    type = "Organization"
    logo = "favicon-512x512.png"
    name = ""
    sameAs = []
    images = ["cover.png"]
    article = []
    newsArticle = []
    blogPosting = ["blog"]
    product = []
